server:
  port: 10086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zsc011021
    url: jdbc:mysql://10.100.164.36:3307/bookshop
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 10.100.164.36
    port: 6379
    password: 20011021
    database: 1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true